### ISSUE TITLE
Site generation functionality fails on external image includes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#242]
In mn-samples-iso, if you remove the `:data-uri-image:` attribute from one document, you will see a failure like this:

```
No such file or directory @ rb_sysopen - /Users/me/src/mn/mn-samples-iso/site/documents/iso-rice-en/images/img01.png
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/image_size-2.1.0/lib/image_size.rb:47:in `initialize'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/image_size-2.1.0/lib/image_size.rb:47:in `open'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/image_size-2.1.0/lib/image_size.rb:47:in `path'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html2doc-1.1.1/lib/html2doc/mime.rb:81:in `image_resize'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.6.2/lib/isodoc/html_function/postprocess.rb:150:in `block in move_images'
```

This is due to the image being external to the file. When resolving any external file, the code should read using a base dir of the original location.

When the `:data-uri-image:` attribute is used, the external image file is embedded into the XML file, so this error does not occur.

**Comment by abunashir** [comment]
Hey @ronaldtse, I think this might be coming from the underlying [isodoc html function](https://github.com/metanorma/isodoc/blob/master/lib/isodoc/html_function/postprocess.rb#L145), and how that tries to handle images.

I don't have that much context on that library, so I can't exactly figure out what's happening there, maybe @opoudjis might be able to help us out on that one?

**Comment by ronaldtse** [comment]
The challenge here is when isodoc builds the HTML, it needs to have the XML point out where the images are. e.g. maybe the XML file can store the base image path?

**Comment by opoudjis** [comment]
> The challenge here is when isodoc builds the HTML, it needs to have the XML point out where the images are. e.g. maybe the XML file can store the base image path?

It'd be more constructive to have that passed on to isodoc as a parameter from metanorma, rather than embed something that non-semantic in the semantic source.

**Comment by ronaldtse** [comment]
All you could pass to isodoc is the "base asset path", where isodoc would be expected to resolve the external references. We would need to make that an optional parameter when Metanorma calls the isodoc gem.

**Comment by opoudjis** [comment]
`@localdir` is the base asset path. It is set currently in isodoc as the parent directory of the filepath passed to isodoc. We want to override that with an option setting, `:base_asset_path`, so that the base asset path can be dissociated from the location of the file.

**Comment by opoudjis** [comment]
So, the base asset path is:

`:base-asset-path:` if given as an Asciidoctor document attribute

`isodoc_options[:baseassetpath]` in `IsoDoc::XXX::HtmlConvert.new(isodoc_options)`, if directly calling Isodoc.

**Comment by opoudjis** [comment]
@abunashir Back to you

**Comment by abunashir** [comment]
@ronaldtse: Let me clarify if I get that right -  we basically need to add an option for `baseassetpath` to the site generator and if user pass that option then we will need to pass it down to the metnorma compile interface?

cc: @opoudjis

**Comment by ronaldtse** [comment]
@abunashir not quite but close! Specifically,

1. when the site generator calls Metanorma to create the XML, it needs to pass the extra option of `:base-asset-path:` where it is set to the location of the `adoc` file. This enables Metanorma XML to contain the base asset path of it.

2. when the site generator converts the XML into resulting formats, the Metanorma processor can read `base-asset-path`   from the XML and know where to find the assets.

**Comment by abunashir** [comment]
@ronaldtse: [The sitemap generator ](https://github.com/metanorma/metanorma-cli/blob/main/lib/metanorma/cli/site_generator.rb#L81) is passing the source file (adoc) as it is without reading it or doing any changes. Unless we want to add custom behaviour for this options, wouldn't it be better to add this functionality to figure out the default base path from metanorma gem side?

**Comment by ronaldtse** [comment]
> Unless we want to add custom behaviour for this options, wouldn't it be better to add this functionality to figure out the default base path from metanorma gem side?

When Metanorma is used on its own for one document, i.e.
```
metanorma ./foo.adoc
```

All external paths are performed using the base relative path from `./`.

In site generation, it looks like the source files get first moved into `site/documents/` so the external assets can't be found?

**Comment by abunashir** [comment]
The xml/html or other issues seems to be fixed but the word file still has the missing image issues - I will do more debugging later to see what exactly is happening there!

> In site generation, it looks like the source files get first moved into `site/documents/` so the external assets can't be found?

**Comment by opoudjis** [comment]
Should we make dataimageuri default to true if not supplied, and opt out rather than opt in? @ronaldtse

**Comment by opoudjis** [comment]
Word operation now fixed.

**Comment by ronaldtse** [comment]
So this particular task needs to be updated to say that when "data-image-uri" is false, then this issue applies.

**Comment by opoudjis** [comment]
Fixed rspec, but are you testing what is done with baseassetpath, @abunashir?

**Comment by abunashir** [comment]
Update: Since, @opoudjis set it as default value, so I assume we don't necessarily need to set the base_path anymore, can we close this one @ronaldtse, or would you still prefer to add it?

**Comment by ronaldtse** [comment]
@abunashir in the case where the value is explicitly not set to the default, we will still have this problem... So we still need to fix it.

**Comment by abunashir** [comment]
Thanks @ronaldtse, with the recent merge on the PR, should it be resolved? can we close this issue?

**Comment by ronaldtse** [comment]
Confirm fixed in metanorma/iso-10303-11 with `:data-uri-image: false`

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/11865/143972351-26d8a7a7-1288-4791-a05c-8421675b26bb.png">
