### ISSUE TITLE
New template still doesn't include dot-files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#91]
In #54 the generated templates is supposed to provide dot-files, but with the latest released gems, I still see:

```sh
bundle exec metanorma new my-generated-doc --type ogc --doctype standard 
Creating my-generated-doc/Makefile
Creating my-generated-doc/appveyor.yml
Creating my-generated-doc/Gemfile
Creating my-generated-doc/Makefile.win
Creating my-generated-doc/sections/clause_7_normative_text.adoc
Creating my-generated-doc/sections/clause_3_references.adoc
Creating my-generated-doc/sections/annex-a.adoc
Creating my-generated-doc/sections/annex-bibliography.adoc
Creating my-generated-doc/sections/clause_2_conformance.adoc
Creating my-generated-doc/sections/clause_0_front_material.adoc
Creating my-generated-doc/sections/clause_8_media_types.adoc
Creating my-generated-doc/sections/annex-history.adoc
Creating my-generated-doc/sections/annex-n.adoc
Creating my-generated-doc/sections/clause_5_conventions.adoc
Creating my-generated-doc/sections/clause_6_informative_text.adoc
Creating my-generated-doc/sections/clause_1_scope.adoc
Creating my-generated-doc/sections/clause_4_terms_and_definitions.adoc
Creating my-generated-doc/UML/README.adoc
Creating my-generated-doc/images/README.adoc
Creating my-generated-doc/abstract_tests/README.adoc
Creating my-generated-doc/code/README.adoc
Creating my-generated-doc/requirements/requirement.adoc
Creating my-generated-doc/requirements/README.adoc
Creating my-generated-doc/requirements/requirements_class.adoc
Creating my-generated-doc/README.adoc
Creating my-generated-doc/document.adoc
Creating my-generated-doc/figures/README.adoc
```

Output of `ls`:
```sh
ls -l my-generated-doc/
total 48
-rw-r--r--   1 myself  staff    69B Jun 19 00:58 Gemfile
-rw-r--r--   1 myself  staff   3.3K Jun 19 00:58 Makefile
-rw-r--r--   1 myself  staff   2.8K Jun 19 00:58 Makefile.win
-rw-r--r--   1 myself  staff   884B Jun 19 00:58 README.adoc
drwxr-xr-x   3 myself  staff    96B Jun 19 00:58 UML/
drwxr-xr-x   3 myself  staff    96B Jun 19 00:58 abstract_tests/
-rw-r--r--   1 myself  staff   551B Jun 19 00:58 appveyor.yml
drwxr-xr-x   3 myself  staff    96B Jun 19 00:58 code/
-rw-r--r--   1 myself  staff   1.5K Jun 19 00:58 document.adoc
drwxr-xr-x   3 myself  staff    96B Jun 19 00:58 figures/
drwxr-xr-x   3 myself  staff    96B Jun 19 00:58 images/
drwxr-xr-x   5 myself  staff   160B Jun 19 00:58 requirements/
drwxr-xr-x  15 myself  staff   480B Jun 19 00:58 sections/
```

Seems like a bug to me?

**Comment by abunashir** [comment]
That's strange, it seems to be working on my end.

**Generation**

<img width="836" alt="Screenshot 2019-06-20 16 24 11" src="https://user-images.githubusercontent.com/1220911/59856880-08880000-9378-11e9-904b-7a98da5ae382.png">

**Listing**

<img width="751" alt="Screenshot 2019-06-20 16 24 51" src="https://user-images.githubusercontent.com/1220911/59856934-22c1de00-9378-11e9-87ac-d5b924b87b1c.png">

@ronaldtse: Could it be your bundle exec is using an old installation? could you please try to execute with `exe/metanorma` script directly?

**Comment by ronaldtse** [comment]
So the problem is that the latest released metanorma-cli still doesn't have this functionality. We need to release it...

**Comment by abunashir** [comment]
That's strange, I thought it was included in `v1.1.8` - https://github.com/metanorma/metanorma-cli/commit/218aca2f3253d0004c9fb409b76a5e3553d3d858, no?

**Comment by ronaldtse** [comment]
```sh
Using metanorma-standoc 1.2.0
Using metanorma-acme 1.2.0
Using metanorma-csand 1.2.0
Using metanorma-csd 1.2.0
Using metanorma-iso 1.2.0
Using metanorma-ietf 1.0.3
Using metanorma-m3d 1.2.0
Using metanorma-nist 0.1.1
Using metanorma-ogc 0.1.0
Using metanorma-unece 0.1.0
Using metanorma-gb 1.2.0
Using metanorma-cli 1.2.0
Bundle updated!
me:~/tmp/csd-subscription-upgrade (master *): bundle exec metanorma new my-generated-doc --type ogc --doctype standard
You've an existing document with the /Users/me/tmp/csd-subscription-upgrade/my-generated-doc
Still want to continue, and overwrite the existing one? (yes/no): yes
Creating my-generated-doc/Makefile
Creating my-generated-doc/appveyor.yml
Creating my-generated-doc/Gemfile
Creating my-generated-doc/Makefile.win
Creating my-generated-doc/sections/clause_7_normative_text.adoc
Creating my-generated-doc/sections/clause_3_references.adoc
Creating my-generated-doc/sections/annex-a.adoc
Creating my-generated-doc/sections/annex-bibliography.adoc
Creating my-generated-doc/sections/clause_2_conformance.adoc
Creating my-generated-doc/sections/clause_0_front_material.adoc
Creating my-generated-doc/sections/clause_8_media_types.adoc
Creating my-generated-doc/sections/annex-history.adoc
Creating my-generated-doc/sections/annex-n.adoc
Creating my-generated-doc/sections/clause_5_conventions.adoc
Creating my-generated-doc/sections/clause_6_informative_text.adoc
Creating my-generated-doc/sections/clause_1_scope.adoc
Creating my-generated-doc/sections/clause_4_terms_and_definitions.adoc
Creating my-generated-doc/UML/README.adoc
Creating my-generated-doc/images/README.adoc
Creating my-generated-doc/abstract_tests/README.adoc
Creating my-generated-doc/code/README.adoc
Creating my-generated-doc/requirements/requirement.adoc
Creating my-generated-doc/requirements/README.adoc
Creating my-generated-doc/requirements/requirements_class.adoc
Creating my-generated-doc/README.adoc
Creating my-generated-doc/document.adoc
Creating my-generated-doc/figures/README.adoc
```

**Comment by abunashir** [comment]
@ronaldtse: Is this one resolved now?

**Comment by ronaldtse** [comment]
@abunashir no, this is still not working. Can you please help fix this?

```
bundle exec metanorma new my-generated-doc --type ogc --doctype standard
Creating my-generated-doc/Makefile
Creating my-generated-doc/appveyor.yml
Creating my-generated-doc/Gemfile
Creating my-generated-doc/Makefile.win
Creating my-generated-doc/sections/clause_7_normative_text.adoc
Creating my-generated-doc/sections/clause_3_references.adoc
Creating my-generated-doc/sections/annex-a.adoc
Creating my-generated-doc/sections/annex-bibliography.adoc
Creating my-generated-doc/sections/clause_2_conformance.adoc
Creating my-generated-doc/sections/clause_0_front_material.adoc
Creating my-generated-doc/sections/clause_8_media_types.adoc
Creating my-generated-doc/sections/annex-history.adoc
Creating my-generated-doc/sections/annex-n.adoc
Creating my-generated-doc/sections/clause_5_conventions.adoc
Creating my-generated-doc/sections/clause_6_informative_text.adoc
Creating my-generated-doc/sections/clause_1_scope.adoc
Creating my-generated-doc/sections/clause_4_terms_and_definitions.adoc
Creating my-generated-doc/UML/README.adoc
Creating my-generated-doc/images/README.adoc
Creating my-generated-doc/abstract_tests/README.adoc
Creating my-generated-doc/code/README.adoc
Creating my-generated-doc/requirements/requirement.adoc
Creating my-generated-doc/requirements/README.adoc
Creating my-generated-doc/requirements/requirements_class.adoc
Creating my-generated-doc/README.adoc
Creating my-generated-doc/document.adoc
Creating my-generated-doc/figures/README.adoc
```

Gemfile.lock:
```
    metanorma-cli (1.2.2)
```
